name: Python Code Check

on: [pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest  # Change this if testing on Windows or macOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            pip install -r requirements-linux.txt
            sudo apt-get update && sudo apt-get install -y dbus libdbus-glib-1-dev
          else
            pip install -r requirements-windows.txt
          fi

      - name: Run Python script
        run: python main.py --help
